easy_outdoor/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("home.urls")),
    path("products/", include("products.urls")),
    path("basket/", include("basket.urls")),
    path("checkout/", include("checkout.urls")),
    path("profile/", include("profiles.urls")),
    path("manage/", include("manage_site.urls")),
    path("newsletter/", include("newsletter.urls")),
    path("summernote/", include("django_summernote.urls")),
]

handler404 = "easy_outdoor.views.page_not_found_view"
handler403 = "easy_outdoor.views.page_forbidden_found_view"
handler500 = "easy_outdoor.views.server_error_view"

home/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", views.index, name="home"),
    path("frequently-asked/", views.frequently_asked_questions,
         name="frequently-asked-questions"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.profile, name="profile"),
    path("order-history", views.order_history, name="order-history"),
    path("rating-form/<int:product_id>", views.load_rating_form,
         name="load-rating-form"),
    path("rate-product/<int:product_id>", views.rate_product,
         name="rate-product"),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_countries.fields import CountryField
from products.models import Product
from django.core.validators import MaxValueValidator


class UserProfile(models.Model):
    """
    Model that stores users personal and delivery
    information for future deliveries
    """
    user = models.OneToOneField(User, related_name="userprofile",
                                on_delete=models.CASCADE)
    default_phone_number = models.CharField(max_length=20,
                                            null=True, blank=True)
    default_country = CountryField(blank_label="Country *",
                                   null=True, blank=True)
    default_postcode = models.CharField(max_length=20,
                                        null=True, blank=True)
    default_town_or_city = models.CharField(max_length=40,
                                            null=True, blank=True)
    default_street_address1 = models.CharField(max_length=80,
                                               null=True, blank=True)
    default_street_address2 = models.CharField(max_length=80,
                                               null=True, blank=True)
    default_county = models.CharField(max_length=80, null=True, blank=True)

    def __str__(self):
        return str(self.user)


@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    """
    Creates or updates the profile of the user
    """
    if created:
        UserProfile.objects.create(user=instance)
    # If user exists then save the profile
    instance.userprofile.save()


class ProductReview(models.Model):
    """Model to store user reviews"""
    user = models.ForeignKey(User, related_name="user",
                             on_delete=models.CASCADE)
    product = models.ForeignKey(
        "products.Product", related_name="product_reviews",
        on_delete=models.CASCADE
        )
    rating = models.DecimalField(
        max_digits=4, decimal_places=2, null=True,
        blank=True, validators=[MaxValueValidator(5)]
        )
    comment = models.TextField(max_length=400, null=False)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("user", "product",)

    def __str__(self):
        return self.comment

profiles/forms.py
from django import forms
from .models import UserProfile, ProductReview
from django.contrib.auth.models import User


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
        ]

    def __init__(self, *args, **kwargs):
        """
        Add placeholders and classes, remove auto-generated
        labels and set autofocus on first field
        """
        super().__init__(*args, **kwargs)
        placeholders = {
            "username": "Username",
            "first_name": "First Name",
            "last_name": "Last Name",
            "email": "Email",
        }

        self.fields["username"].help_text = ""
        self.fields["username"].error_messages.update({
            "Required": "150 characters or fewer. Letters, digits \
                and @/./+/-/_ only.",
        })
        for field in self.fields:
            if self.fields[field].required:
                placeholder = f"{placeholders[field]} *"
            else:
                placeholder = placeholders[field]
            self.fields[field].widget.attrs["placeholder"] = placeholder
            self.fields[field].label = False


class UserDeliveryForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ("user",)

    def __init__(self, *args, **kwargs):
        """
        Add placeholders and classes, remove auto-generated
        labels and set autofocus on first field
        """
        super().__init__(*args, **kwargs)
        placeholders = {
            "default_phone_number": "Phone Number",
            "default_postcode": "Postal Code",
            "default_town_or_city": "Town or City",
            "default_street_address1": "Street Address 1",
            "default_street_address2": "Street Address 2",
            "default_county": "County, State or Locality",
        }

        self.fields["default_phone_number"].widget.attrs["autofocus"] = True
        for field in self.fields:
            if field != "default_country":
                if self.fields[field].required:
                    placeholder = f"{placeholders[field]} *"
                else:
                    placeholder = placeholders[field]
                self.fields[field].widget.attrs["placeholder"] = placeholder
            self.fields[field].label = False


class ProductReviewForm(forms.ModelForm):
    class Meta:
        model = ProductReview
        exclude = ("user", "product",)

        widgets = {
            "comment": forms.Textarea(attrs={
                "placeholder": "Please leave your feedback in this box."}),
        }

profiles/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.db.models import Avg
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from .models import UserProfile, ProductReview
from checkout.models import Order, OrderLineItem
from products.models import Product
from .forms import UserProfileForm, UserDeliveryForm, ProductReviewForm
from django.contrib import messages
from django.forms.models import model_to_dict


def profile(request):
    """ Display user profiles """
    user = request.user
    profile = get_object_or_404(UserProfile, user=request.user)

    if request.method == "POST":
        user_form = UserProfileForm(request.POST, instance=user)
        delivery_form = UserDeliveryForm(request.POST, instance=profile)
        if delivery_form.is_valid() and user_form.is_valid():
            user_form.save()
            delivery_form.save()
            messages.success(request, "Profile updated successfully")
            return redirect(reverse("profile"))
        else:
            messages.error(
                request,
                "Update failed. Please ensure the form is valid."
                )
    else:
        user_form = UserProfileForm(instance=user)
        delivery_form = UserDeliveryForm(instance=profile)
    orders = profile.orders.all()

    template = "profiles/profile.html"
    context = {
        "user": user,
        "profile": profile,
        "user_form": user_form,
        "delivery_form": delivery_form,
    }

    return render(request, template, context)


def order_history(request):
    """ Display user's order history """
    profile = get_object_or_404(UserProfile, user=request.user)
    orders = Order.objects.filter(user_profile=profile)
    ordered_orders = orders.order_by('-date')
    user = request.user
    reviews = ProductReview.objects.filter(user=user)

    template = "profiles/order-history.html"
    context = {
        "orders": ordered_orders,
        "reviews": reviews,
    }

    return render(request, template, context)


def load_rating_form(request, product_id):
    """Loads form for user to leave a rating"""
    product = get_object_or_404(Product, id=product_id)
    rating_form = ProductReviewForm()
    template = "profiles/rate-product.html"
    context = {
        "form": rating_form,
        "product": product,
    }
    return render(request, template, context)


def rate_product(request, product_id):
    """Handles and submits rating"""
    product = get_object_or_404(Product, id=product_id)
    rating_form = ProductReviewForm(data=request.POST)
    user = request.user
    rating = request.POST.get("rating")
    if not rating:
        rating = 0
    else:
        rating = rating
    try:
        if rating_form.is_valid():
            rating_form.instance.user = user
            rating_form.instance.product = product
            rating_form.instance.rating = rating
            rating_form.instance.comment = request.POST.get("comment")
            rating_form.save()
            # Sets product rating to average of all ratings
            product_ratings = ProductReview.objects.filter(product=product)
            average_rating = product_ratings.aggregate(
                Avg("rating"))["rating__avg"]
            product.rating = round(average_rating, 2)
            product.save()
            messages.success(request, f"Product Rated {rating} stars! \
                Thank you for your feedback.")
        else:
            messages.error(request, "The form was invalid and could \
                 not be processed. Please try again.")
            rating_form = ProductReviewForm()

    except IntegrityError:
        messages.error(
            request,
            "Error: You have already reviewed this product."
            )

    return render(request, "home/index.html")

profiles/templates/profiles/order-history.html
{% extends "base.html" %}
{% load static %}
{% load basket_tools %}


{% block extra_css %}
<link rel="stylesheet" href="{% static 'profiles/css/profile.css' %}">
{% endblock %}

{% block content %}

<section class="profile-section">
    <div class="container pb-5">
        <div class="row">
            <h2 class="px-3 fs-1 text-center">Order History</h2>
        </div>
        <div class="row">
            <h3 class="d-none d-md-block border-bottom">Orders</h3>
            <div class="px-3 mt-3 col-12 col-md-6 order-2 order-md-1">
                {% if orders %}
                <div class="accordion accordion-flush" id="accordionFlushExample">
                    {% for order in orders %}
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="flush-headingOne">

                            <button class="accordion-button collapsed px-2" type="button" data-bs-toggle="collapse"
                                data-bs-target="#flush-collapse-{{ order.order_number }}" aria-expanded="false"
                                aria-controls="flush-collapse-{{ order.order_number }}">
                                <strong>{{ forloop.counter }}. {{ order.date | date:"M d, Y"}} 
                                    - {{ order.lineitems.all | length }} Items - 
                                    £{{ order.grand_total }}
                                    <span class="sale"></span>
                                </strong>
                            </button>
                        </h2>
                        <div id="flush-collapse-{{ order.order_number }}" class="accordion-collapse collapse"
                            aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                            <div class="accordion-body p-0">
                                <div class="p-2">
                                    <p class="mb-0"><strong>Number:</strong> {{ order.order_number }}</p>
                                    <p><strong>Date:</strong> {{ order.date | date:"M d, Y" }}</p>
                                </div>
                                <div class="p-2 border-bottom">
                                    <h4 class="fw-bold">Order Items</h4>
                                    {% for item in order.lineitems.all %}
                                    <p class="mb-3">
                                        <strong>{{ forloop.counter }}.</strong>
                                        <strong>{{ item.product }}</strong> |
                                        <strong>Qty:</strong> {{ item.quantity }} |
                                        <strong>Size:</strong> {{ item.product_size }} |
                                        <strong>£</strong>{{ item.lineitem_total }} |
                                        {% if reviews %}
                                            {% for r in reviews %}
                                                {% if r.product == item.product %}
                                                <p class="toast-success product-review">You have already rated this product.</p>  
                                                {% endif %}
                                            {% endfor %}
                                        {% endif %}
                                        <a class="rated" href="{% url 'load-rating-form' product_id=item.product.id %}">Rate This Item</a>
                                    </p>
                                    {% endfor %}
                                </div>
                                <div class="p-2 border-bottom">
                                    <h4 class="fw-bold">Delivery Info:</h4>
                                    <ul class="order-info-list p-0">
                                        <li>{{ order.full_name }}</li>
                                        <li>{{ order.email }}</li>
                                        <li>{{ order.phone_number }}</li>
                                        <li>{{ order.street_address1 }}</li>
                                        {% if order.street_address2 %}
                                            <li>{{ order.street_address2 }}</li>
                                        {% endif %}
                                        {% if order.county %}
                                            <li>{{ order.county }}</li>
                                        {% endif %}
                                        <li>{{ order.postcode }}</li>
                                        <li>{{ order.town_or_city }}</li>
                                        <li>{{ order.country }}</li>
                                    </ul>
                                </div>
                                <div class="p-2">
                                    <h4>Cost:</h4>
                                    <p class="mb-0"><strong>Order Total:</strong> {{ order.order_total }}</p>
                                    <p class="mb-0"><strong>Delivery Cost:</strong> {{ order.delivery_cost }}</p>
                                    <p class="mb-0"><strong>Grand Total:</strong> {{ order.grand_total }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% else %}
                <div class="mt-3 text-center">
                    <h4 class="fw-bold">You haven't made any orders yet.</h4>
                    <a href="{% url 'products' %}" class="shop-btn px-2 py-1">Shop Now</a>
                </div>
                {% endif %}
            </div>
            <div id="order-history-panel" class="mx-auto mt-3 py-4 col-12 col-md-6 order-1 order-md-2 rounded info-panel d-flex flex-column justify-content-center align-content-center">
                <div class="px-3 text-center text-white">
                    <div class="logo mb-3"></div>
                    <h3 class="fs-1">Hello {{ user.first_name }}.</h3>
                    <p class="mx-auto fs-5">This is your order history page.
                        Here you can view previous orders, this is useful if any issues arise later on in the order
                        process.</p>
                    <p class="mx-auto fs-5">If you are having trouble with an order please contact us.</p>
                    <a href="{% url 'contact-form' %}" class="shop-btn text-decoration-none px-5 py-1">Contact Form</a>
                </div>
            </div>
        </div>
</section>

{% endblock %}

{% block postloadjs %}
<script>
    $(document).ready(function () {
        if ( $(".product-review").length ) {
            $(".product-review").next().hide();
        }
    });
</script>
{% endblock %}

profiles/templates/profiles/order_history.html
{% extends "base.html" %}
{% load static %}
{% load basket_tools %}


{% block extra_css %}
<link rel="stylesheet" href="{% static 'profiles/css/profile.css' %}">
{% endblock %}

{% block content %}

<section class="profile-section">
    <div class="container pb-5">
        <div class="row">
            <h2 class="px-3 fs-1 text-center">Order History</h2>
        </div>
        <div class="row">
            <h3 class="d-none d-md-block border-bottom">Orders</h3>
            <div class="px-3 mt-3 col-12 col-md-6 order-2 order-md-1">
                {% if orders %}
                <div class="accordion accordion-flush" id="accordionFlushExample">
                    {% for order in orders %}
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="flush-headingOne">

                            <button class="accordion-button collapsed px-2" type="button" data-bs-toggle="collapse"
                                data-bs-target="#flush-collapse-{{ order.order_number }}" aria-expanded="false"
                                aria-controls="flush-collapse-{{ order.order_number }}">
                                <strong>{{ forloop.counter }}. {{ order.date | date:"M d, Y"}} 
                                    - {{ order.lineitems.all | length }} Items - 
                                    £{{ order.grand_total }}
                                    <span class="sale"></span>
                                </strong>
                            </button>
                        </h2>
                        <div id="flush-collapse-{{ order.order_number }}" class="accordion-collapse collapse"
                            aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                            <div class="accordion-body p-0">
                                <div class="p-2">
                                    <p class="mb-0"><strong>Number:</strong> {{ order.order_number }}</p>
                                    <p><strong>Date:</strong> {{ order.date | date:"M d, Y" }}</p>
                                </div>
                                <div class="p-2 border-bottom">
                                    <h4 class="fw-bold">Order Items</h4>
                                    {% for item in order.lineitems.all %}
                                    <p class="mb-3">
                                        <strong>{{ forloop.counter }}.</strong>
                                        <strong>{{ item.product }}</strong> |
                                        <strong>Qty:</strong> {{ item.quantity }} |
                                        <strong>Size:</strong> {{ item.product_size }} |
                                        <strong>£</strong>{{ item.lineitem_total }} |
                                        {% if reviews %}
                                            {% for r in reviews %}
                                                {% if r.product == item.product %}
                                                <p class="toast-success">You have already rated this product.</p>  
                                                {% else %}
                                                <a class="unrated" href="{% url 'load-rating-form' product_id=item.product.id %}">Rate This Item</a>
                                                {% endif %}
                                            {% endfor %}
                                        {% else %}
                                        <a class="rated" href="{% url 'load-rating-form' product_id=item.product.id %}">Rate This Item</a>
                                        {% endif %}
                                    </p>
                                    {% endfor %}
                                </div>
                                <div class="p-2 border-bottom">
                                    <h4 class="fw-bold">Delivery Info:</h4>
                                    <ul class="order-info-list p-0">
                                        <li>{{ order.full_name }}</li>
                                        <li>{{ order.email }}</li>
                                        <li>{{ order.phone_number }}</li>
                                        <li>{{ order.street_address1 }}</li>
                                        {% if order.street_address2 %}
                                            <li>{{ order.street_address2 }}</li>
                                        {% endif %}
                                        {% if order.county %}
                                            <li>{{ order.county }}</li>
                                        {% endif %}
                                        <li>{{ order.postcode }}</li>
                                        <li>{{ order.town_or_city }}</li>
                                        <li>{{ order.country }}</li>
                                    </ul>
                                </div>
                                <div class="p-2">
                                    <h4>Cost:</h4>
                                    <p class="mb-0"><strong>Order Total:</strong> {{ order.order_total }}</p>
                                    <p class="mb-0"><strong>Delivery Cost:</strong> {{ order.delivery_cost }}</p>
                                    <p class="mb-0"><strong>Grand Total:</strong> {{ order.grand_total }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% else %}
                <div class="mt-3 text-center">
                    <h4 class="fw-bold">You haven't made any orders yet.</h4>
                    <a href="{% url 'products' %}" class="shop-btn px-2 py-1">Shop Now</a>
                </div>
                {% endif %}
            </div>
            <div id="order-history-panel" class="mx-auto mt-3 py-4 col-12 col-md-6 order-1 order-md-2 rounded info-panel d-flex flex-column justify-content-center align-content-center">
                <div class="px-3 text-center text-white">
                    <div class="logo mb-3"></div>
                    <h3 class="fs-1">Hello {{ user.first_name }}.</h3>
                    <p class="mx-auto fs-5">This is your order history page.
                        Here you can view previous orders, this is useful if any issues arise later on in the order
                        process.</p>
                    <p class="mx-auto fs-5">If you are having trouble with an order please contact us.</p>
                    <a href="{% url 'contact-form' %}" class="shop-btn text-decoration-none px-5 py-1">Contact Form</a>
                </div>
            </div>
        </div>
</section>

{% endblock %}

{% block postloadjs %}
<script>
    $(document).ready(function () {
        $('.unrated').hide();
        $('.rated').hide();
        $('.unrated:first').show();
        $('.rated:first').show();
    });
</script>
{% endblock %}

profiles/templates/profiles/product-review.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/manage_site.css' %}">
<link rel="stylesheet" href="{% static 'css/rating-selector.css' %}">
{% endblock %}

{% block content %}

<section class="admin-section">
    <div class="container">
        <div class="row">
            <div class="text-center mx-auto col-12 col-md-6 admin-form rounded mt-3">
                <h2 class="border-bottom">Rate {{ product }}</h2>
                <h5 class="fw-bold">Happy with this product? Let us know!</h5>
                <form method="POST" action="{% url 'rate-product' product_id=product.id %}">
                    {% csrf_token %}
                    <div>
                        {% include 'profiles/includes/rating-selector.html' %}
                    </div>
                    {{ form.comment | as_crispy_field }}
                    <a class="white-btn px-3 py-1" href="{% url 'order-history' %}">Cancel</a>
                    <input class="shop-btn px-3 py-1" type="submit" value="Submit">
                </form>
            </div>
        </div>
    </div>

</section>

{% endblock %}
{% block postloadjs %}
{{ block.super }}

<script type="text/javascript">
    $( document ).ready(function() {
        $('input[name="rating"]:checked').val();
        $("label[for='id_comment']").hide()
    })
</script>

{% endblock %}

profiles/templates/profiles/profile.html
{% extends "base.html" %}
{% load static %}
{% load basket_tools %}


{% block extra_css %}
<link rel="stylesheet" href="{% static 'profiles/css/profile.css' %}">
{% endblock %}

{% block content %}

<section class="profile-section">
    <div class="container pb-5">
        <div class="row">
            <h2 class="px-3 fs-1 text-center">Profile</h2>
        </div>
        <div class="row">
            <form id="userForm" class="px-3 mt-3 col-12 col-md-6 order-2 order-md-1" action="{% url 'profile' %}" method="POST" id="profile-update-form">
                {% csrf_token %}
                <div class="">
                    <h3>Personal Info</h3>
                    {{ user_form|crispy }}
                </div>
                <div class="pt-3">
                    <h3>Delivery Details</h3>
                    {{ delivery_form|crispy }}
                </div>
                <a class="mt-2 white-btn px-2 py-1" href="{% url 'account_change_password' %}">Change Password</a>
                <button type="submit" class="mt-2 shop-btn px-4 py-1">Update</button>
            </form>
           <div class="mx-auto mt-3 py-4 col-12 col-md-6 order-1 order-md-2 rounded info-panel d-flex flex-column justify-content-center align-content-center">
            <div class="px-3 text-center text-white">
                <div class="logo mb-3"></div>
                <h3 class="fs-1">Hello {{ user.first_name }}.</h3>
                <p class="mx-auto fs-5">This is your profile page. 
                    Here you can add or update your personal information
                    to make ordering in the future even <strong class="sale">easier</strong>! </p>
                <p class="mx-auto fs-5">Thank you for choosing us :)</p>
            </div>
           </div>
        </div>
</section>

{% endblock %}

{% block postloadjs %}
<!-- Page script and form validation -->
<script src="{% static 'profiles/js/profile_form.js' %}"></script>
{% endblock %}

profiles/templates/profiles/rate-product.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'manage_site/css/manage-site.css' %}">
<link rel="stylesheet" href="{% static 'profiles/css/rating-selector.css' %}">
{% endblock %}

{% block content %}

<section class="admin-section">
    <div class="container">
        <div class="row">
            <div class="text-center mx-auto col-12 col-md-6 admin-form rounded mt-3">
                <h2 class="border-bottom">Rate {{ product }}</h2>
                <h5 class="fw-bold">Happy with this product? Let us know!</h5>
                <form method="POST" id="reviewForm" action="{% url 'rate-product' product_id=product.id %}">
                    {% csrf_token %}
                    <div>
                        {% include "profiles/includes/rating-selector.html" %}
                    </div>
                    <div class="mb-3">
                        {{ form.comment | as_crispy_field }}
                    </div>
                    <a class="white-btn px-3 py-1" href="{% url 'order-history' %}">Cancel</a>
                    <input id="reviewSubmit" class="shop-btn px-3 py-1" type="submit" value="Submit">
                </form>
            </div>
        </div>
    </div>

</section>

{% endblock %}

{% block postloadjs %}
<!-- Page script and form validation -->
<script src="{% static 'profiles/js/rate_product.js' %}"></script>
{% endblock %}