easy_outdoor/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("home.urls")),
    path("products/", include("products.urls")),
    path("basket/", include("basket.urls")),
    path("checkout/", include("checkout.urls")),
    path("profile/", include("profiles.urls")),
    path("manage/", include("manage_site.urls")),
    path("newsletter/", include("newsletter.urls")),
    path("summernote/", include("django_summernote.urls")),
]

handler404 = "easy_outdoor.views.page_not_found_view"
handler403 = "easy_outdoor.views.page_forbidden_found_view"
handler500 = "easy_outdoor.views.server_error_view"

home/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", views.index, name="home"),
    path("frequently-asked/", views.frequently_asked_questions,
         name="frequently-asked-questions"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manage_site/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.manage_site, name="manage-site"),
    path("add-product/", views.AddProduct.as_view(), name="add-product"),
    path("update-product/<int:pk>", views.UpdateProduct.as_view(),
         name="update-product"),
    path("delete-product/<int:pk>", views.DeleteProduct.as_view(),
         name="delete-product"),
    path("update-size-stock/<int:pk>", views.UpdateSizeStock.as_view(),
         name="update-size-stock"),
    path("update-regular-stock/<int:pk>", views.UpdateRegularStock.as_view(),
         name="update-regular-stock"),
    path("order-details/<int:pk>", views.OrderDetails.as_view(),
         name="order-details"),
    path("update-profile/<int:user_id>", views.update_profile,
         name="update-profile"),
    path("delete-profile/<int:pk>", views.DeleteProfile.as_view(),
         name="delete-profile"),
    path("delete-email/<int:pk>", views.DeleteEmail.as_view(),
         name="delete-email"),
]

manage_site/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.utils.text import slugify
from django.core.validators import MaxValueValidator


class Category(models.Model):
    """Model to store categories for the product model"""
    name = models.CharField(max_length=200)
    friendly_name = models.CharField(max_length=200, null=True, blank=True)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.friendly_name:
            self.friendly_name = self.name.capitalize()
        if not self.rating:
            self.rating = 0
        return super().save(*args, **kwargs)


class Product(models.Model):
    """Model to store product information and characteristics"""
    category = models.ForeignKey(
        "Category", null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=200)
    desc = models.TextField()
    slug = models.SlugField(max_length=50, unique=True, blank=True, null=True)
    has_sizes = models.BooleanField(blank=False, default=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    sale_price = models.DecimalField(max_digits=6, decimal_places=2,
                                     null=True, blank=True)
    rating = models.DecimalField(max_digits=4, decimal_places=2, null=True,
                                 blank=True, validators=[MaxValueValidator(5)])
    image = models.ImageField(null=True, blank=True)
    image_url = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.name

    # Auto generates the slugfield
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        if not self.rating:
            self.rating = 0
        return super().save(*args, **kwargs)

    # Rounds to nearest .5 for the star rating
    def round_rating(self):
        return round(self.rating * 2) / 2


class SizeStock(models.Model):
    """Model to keep stock of products with sizes"""
    product = models.ForeignKey("Product", related_name="size_stock",
                                on_delete=models.CASCADE)
    xs = models.IntegerField("extra small", null=True, blank=True)
    s = models.IntegerField("small", null=True, blank=True)
    m = models.IntegerField("medium", null=True, blank=True)
    l = models.IntegerField("large", null=True, blank=True)
    xl = models.IntegerField("extra large", null=True, blank=True)

    def __str__(self):
        return str(self.product.name + "Size Stock")


class RegularStock(models.Model):
    """Model to keep stock of products without sizes"""
    product = models.ForeignKey("Product", related_name="regular_stock",
                                on_delete=models.CASCADE)
    stock = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return str(self.product.name + "Regular Stock")

manage_site/forms.py
from django import forms
from django.contrib.auth.models import User
from products.models import Product, SizeStock, RegularStock


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            "category",
            "name",
            "slug",
            "desc",
            "has_sizes",
            "price",
            "sale_price",
            "image_url"
            ]
        localized_fields = ["price"]

        widgets = {
            "name": forms.TextInput(
                attrs={"placeholder": "Product Name *"}),
            "slug": forms.TextInput(
                attrs={"placeholder": "Slug (Auto loads if blank)"}),
            "desc": forms.Textarea(
                attrs={"placeholder": "Product description *", "rows": 7}),
            "price": forms.NumberInput(
                attrs={"placeholder": "Price (£)"}),
            "sale_price": forms.NumberInput(
                attrs={"placeholder": "Discount Price (£)"}),
            "image_url": forms.URLInput(
                attrs={"placeholder": "Image URL"}),
        }


class SizeStockForm(forms.ModelForm):
    class Meta:
        model = SizeStock
        fields = ["xs", "s", "m", "l", "xl"]

        widgets = {
            "xs": forms.NumberInput(attrs={"placeholder": "XS"}),
            "s": forms.NumberInput(attrs={"placeholder": "S"}),
            "m": forms.NumberInput(attrs={"placeholder": "M"}),
            "l": forms.NumberInput(attrs={"placeholder": "L"}),
            "xl": forms.NumberInput(attrs={"placeholder": "XL"}),
        }


class RegularStockForm(forms.ModelForm):
    class Meta:
        model = RegularStock
        fields = ["stock"]

        widgets = {
            "stock": forms.NumberInput(attrs={"placeholder": "Quantity"}),
        }

manage_site/views.py
from django.shortcuts import render, reverse, get_object_or_404, redirect
from products.models import Product, SizeStock, RegularStock
from checkout.models import Order
from profiles.models import UserProfile
from newsletter.models import MailingList
from profiles.forms import UserDeliveryForm, UserProfileForm
from .forms import ProductForm, RegularStockForm, SizeStockForm

from django.views.generic import CreateView, UpdateView, DeleteView, DetailView
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import User

from django import forms
from itertools import chain


@user_passes_test(lambda user: user.is_staff)
def manage_site(request):
    """Displays site management template for admin"""
    template = "manage_site/manage-site.html"

    products = Product.objects.all()
    size_stock = SizeStock.objects.all()
    regular_stock = RegularStock.objects.all()
    orders = Order.objects.all()
    mailing_list = MailingList.objects.all()
    profiles = UserProfile.objects.all()

    context = {
        "products": products,
        "regular_stock": regular_stock,
        "size_stock": size_stock,
        "orders": orders,
        "mailing_list": mailing_list,
        "profiles": profiles,
    }

    return render(request, template, context)


# CRUD for products for admin area
class AddProduct(SuccessMessageMixin, UserPassesTestMixin, CreateView):
    """Creates product model"""
    model = Product
    form_class = ProductForm
    template_name = "manage_site/product-add.html"
    success_message = "Product Added!"

    def test_func(self):
        return self.request.user.is_staff

    def get_success_url(self):
        return reverse("manage-site")


class UpdateProduct(SuccessMessageMixin, UserPassesTestMixin, UpdateView):
    """Updates product model"""
    model = Product
    template_name = "manage_site/product-update.html"
    fields = "__all__"
    success_message = "Product Updated!"

    def get_initial(self):
        initial_values = super(UpdateProduct, self).get_initial()
        return initial_values

    def get_form_class(self):
        return ProductForm

    def test_func(self):
        return self.request.user.is_staff

    def get_success_url(self):
        return reverse("manage-site")


class DeleteProduct(SuccessMessageMixin, UserPassesTestMixin, DeleteView):
    model = Product
    delete_message = "Product Deleted!"
    template_name = "manage_site/product-delete.html"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.delete_message)
        return super(DeleteProduct, self).delete(request, *args, **kwargs)

    def test_func(self):
        return self.request.user.is_staff

    def get_success_url(self):
        return reverse("manage-site")


# CRUD for stock for admin area
class UpdateSizeStock(SuccessMessageMixin, UserPassesTestMixin, UpdateView):
    """Updates product model"""
    model = SizeStock
    template_name = "manage_site/size-stock-update.html"
    fields = "__all__"
    success_message = "Product size stock updated!"

    def get_initial(self):
        initial_values = super(UpdateSizeStock, self).get_initial()
        return initial_values

    def get_form_class(self):
        return SizeStockForm

    def test_func(self):
        return self.request.user.is_staff

    def get_success_url(self):
        return reverse("manage-site")


class UpdateRegularStock(SuccessMessageMixin, UserPassesTestMixin, UpdateView):
    """Updates product model"""
    model = RegularStock
    template_name = "manage_site/regular-stock-update.html"
    success_message = "Product Stock Updated!"

    def get_initial(self):
        initial_values = super().get_initial()
        return initial_values

    def get_form_class(self):
        return RegularStockForm

    def test_func(self):
        return self.request.user.is_staff

    def get_success_url(self):
        return reverse("manage-site")


# View order details
class OrderDetails(SuccessMessageMixin, UserPassesTestMixin, DetailView):
    """Displays immutable order details"""
    model = Order
    template_name = "manage_site/order-detail.html"

    def test_func(self):
        return self.request.user.is_staff


# Crud for users
@user_passes_test(lambda user: user.is_staff)
def update_profile(request, user_id):
    """ Displays form and updates users information """
    user = get_object_or_404(User, id=user_id)
    profile = get_object_or_404(UserProfile, user=user)

    if request.method == "POST":
        user_form = UserProfileForm(request.POST, instance=user)
        delivery_form = UserDeliveryForm(request.POST, instance=profile)
        if delivery_form.is_valid() and user_form.is_valid():
            user_form.save()
            delivery_form.save()
            messages.success(request, "Profile updated successfully")
            return redirect(reverse("manage-site"))
        else:
            messages.error(
                request,
                "Update failed. Please ensure the form is valid."
                )
            raise ValidationError(
                    f"Your form was not updated, please fill out \
                    the form correctly."
                )
    else:
        user_form = UserProfileForm(instance=user)
        delivery_form = UserDeliveryForm(instance=profile)
    orders = profile.orders.all()

    template = "manage_site/profile-update.html"
    context = {
        "user": user,
        "profile": profile,
        "user_form": user_form,
        "delivery_form": delivery_form,
    }

    return render(request, template, context)


class DeleteProfile(UserPassesTestMixin, DeleteView):
    """Deletes user profile from the database"""
    model = User
    delete_message = "User Deleted!"
    template_name = "manage_site/profile-delete.html"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.delete_message)
        return super(DeleteProfile, self).delete(request, *args, **kwargs)

    def test_func(self):
        return self.request.user.is_staff

    def get_success_url(self):
        return reverse("manage-site")


# Delete email from newsletter database
class DeleteEmail(UserPassesTestMixin, DeleteView):
    """Deletes user profile from the database"""
    model = MailingList
    delete_message = "Email removed from mailing list!"
    template_name = "manage_site/email-delete.html"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.delete_message)
        return super(DeleteEmail, self).delete(request, *args, **kwargs)

    def test_func(self):
        return self.request.user.is_staff

    def get_success_url(self):
        return reverse("manage-site")

manage_site/templates/manage_site/add-product.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/manage_site.css' %}">
{% endblock %}

{% block content %}

<section class="admin-section">
    <div class="container">
        <div class="row">
            <div class="mx-auto col-12 col-md-6 admin-form rounded mt-3">
                <h2>Add Product</h2>
                <form method="POST">
                    {% csrf_token %}
                    {{ form.category | as_crispy_field }}
                    {{ form.name | as_crispy_field }}
                    {{ form.desc| as_crispy_field }}
                    {{ form.slug | as_crispy_field }}
                    <p class="mb-0">Sized Item:</p>
                    <div class="form-check form-switch" id="div_id_has_sizes" id="div_id_has_sizes" id="id_has_sizes">
                        <input class="form-check-input" name="has_sizes" type="checkbox" id="flexSwitchCheckDefault" checked="">
                    </div>
                    <div class="d-flex mt-2 justify-content-between">
                        {{ form.price | as_crispy_field }}
                        {{ form.sale_price | as_crispy_field }}
                    </div>
                    {{ form.image_url | as_crispy_field }}
                    <input class="shop-btn px-3 py-1" type="submit" value="Add Product">
                </form>
            </div>
        </div>
    </div>

</section>

{% endblock %}
{% block postloadjs %}
{{ block.super }}
<script type="text/javascript">
    $(document).ready(function () {
        $('label').hide()
        // Change option text
        $('select option:contains("---------")').text('Category *');
        $('select option:contains("jackets_coats")').text('Jackets & Coats');
        $('select option:contains("equipment")').text('Equipment');
        $('select option:contains("trousers")').text('Trousers');
        $('select option:contains("fleeces_jumpers")').text('Fleeces & Jumpers');
        $('select option:contains("footwear")').text('Footwear');
        $('select option:contains("t-shirts")').text('T-Shirts');
        $('select option:contains("socks")').text('Socks');
        $('select option:contains("sunglasses")').text('Sunglasses');
        $('select option:contains("headwear")').text('Headwear');
        $('select option:contains("gloves")').text('Gloves');
    });
</script>
{% endblock %}

manage_site/templates/manage_site/email-delete.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'manage_site/css/manage-site.css' %}">
{% endblock %}

{% block content %}

<section class="admin-section">
    <div class="container">
        <div class="row text-center">
            <div class="p-3 bg-white mx-auto col-12 col-md-6 admin-form rounded mt-3">
                <h2>Delete Subscription</h2>
                <p>Are you sure you want to remove this user from the mailing list?</p>
                <p class="mb-0">Email:</p>
                <p class="fw-bold">{{ object }}</p>
                
                <form method="post">{% csrf_token %}
                    {{ form }}
                    <a class="white-btn px-3 py-1" href="{% url 'manage-site' %}">Cancel</a>
                    <input class="shop-btn px-3 py-1" type="submit" value="Confirm">
                </form>
            </div>
        </div>
    </div>

</section>

{% endblock %}

manage_site/templates/manage_site/manage-site.html
{% extends "base.html" %}
{% load static %}
{% load basket_tools %}


{% block extra_css %}
<link rel="stylesheet" href="{% static 'manage_site/css/manage-site.css' %}">
{% endblock %}

{% block content %}

<section class="admin-section mt-5">

    <!-- Taken from bootstrap examples -->
    <div class="container pb-5">
        <div class="row">
            <h2 class="fs-1 fw-bold text-center">Admin</h2>
        </div>
        <div class="row">
            <div id="adminMenu" class="rounded col-12 col-md-3 col-lg-2 d-flex flex-column">
                <div class="mx-auto my-0 my-4 logo"></div>
                <ul class="nav nav-pills flex-column mb-auto">
                    <li class="nav-item">
                        <a href="#" class="admin-menu-link rounded active" aria-current="page">
                            <i class="fa-solid fa-shirt"></i>
                            Products
                        </a>
                    </li>
                    <li>
                        <a href="#" class="admin-menu-link rounded">
                            <i class="fa-solid fa-boxes-packing"></i>
                            Stock
                        </a>
                    </li>
                    <li>
                        <a href="#" class="admin-menu-link rounded">
                            <i class="fa-solid fa-box-archive"></i>
                            Orders
                        </a>
                    </li>
                    <li>
                        <a href="#" class="admin-menu-link rounded">
                            <i class="fa-solid fa-user"></i>
                            Users
                        </a>
                    </li>
                    <li>
                        <a href="#" class="admin-menu-link rounded">
                            <i class="fa-solid fa-envelope"></i>
                            Mailing List
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'admin:index' %}" class="admin-btn rounded">
                            <i class="fa-solid fa-gear"></i>
                            Django
                        </a>
                    </li>

                </ul>
            </div>

            <div class="mx-auto col-12 col-md-9 col-lg-10">
                <div class="container">

                    <div class="admin-db" id="manage-products">
                        {% include "manage_site/includes/manage-products.html" %}
                    </div>
                    <div class="admin-db d-none" id="manage-stock">
                        {% include "manage_site/includes/manage-stock.html" %}
                    </div>
                    <div class="admin-db d-none" id="manage-orders">
                        {% include "manage_site/includes/manage-orders.html" %}
                    </div>
                    <div class="admin-db d-none" id="manage-users">
                        {% include "manage_site/includes/manage-users.html" %}
                    </div>
                    <div class="admin-db d-none" id="manage-mailing">
                        {% include "manage_site/includes/manage-newsletter.html" %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script src="{% static 'manage_site/js/manage_site.js' %}"></script>
{% endblock %}

manage_site/templates/manage_site/order-detail.html
{% extends "base.html" %}
{% load static %}
{% load basket_tools %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'manage_site/css/manage-site.css' %}">
{% endblock %}

{% block content %}
<section class="admin-section">
    <div class="order-detail container bg-white rounded text-center">
        <h2>Order Detail</h2>
        <p>
            View the order summary below for order made on <strong>{{ order.date | date:"d/m/y" }}</strong>.
        </p>
        <p class="mx-auto w-75">
            This record should not be altered or deleted.
            Access the Django admin panel if any actions <strong>must</strong> be taken.
        </p>
        <a class="text-decoration-none d-inline-block shop-btn px-2 py-1 mb-3" href="{% url 'admin:index' %}">Django Admin</a>

        <div class="row">
            <div>
                <h3 class="fw-bold">Order Number:</h3>
                <p>{{ order.order_number | lower }}</p>
            </div>
        </div>
        <div class="row mb-3">
            <div>
                <h3 class="fw-bold">Delivery Details:</h3>
                <p class="mb-0">{{ order.full_name }}</p>
                <p class="mb-0">{{ order.email }}</p>
                <p class="mb-0">{{ order.phone_number }}</p>
                {% if order.user_profile %}
                <p class="mb-0">{{ order.user_profile }}</p>
                {% endif %}
                <p class="mb-0">{{ order.street_address1 }},</p>
                {% if order.street_address2 %}
                <p class="mb-0">{{ order.street_address1 }},</p>
                {% endif %}
                {% if order.county %}
                <p class="mb-0">{{ order.county }},</p>
                {% endif %}
                <p class="mb-0">{{ order.postcode }},</p>
                <p class="mb-0">{{ order.town_or_city }},</p>
                <p class="mb-0">{{ order.country.name }}</p>
            </div>
        </div>

        <div class="row">
            <div>
                <h3 class="fw-bold">Items</h3>
                <div class="border-bottom row item-row my-2">
                    <div class="">
                        <div class="p-0">
                            {% for item in order.lineitems.all %}
                            <p class="mb-3">
                                <strong>{{ forloop.counter }}.</strong>
                                <strong>{{ item.product }}</strong> |
                                <strong>Qty:</strong> {{ item.quantity }} |
                                <strong>Size:</strong> {{ item.product_size }} |
                                <strong>£</strong>{{ item.lineitem_total }} |
                            </p>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <h3 class="fw-bold">Cost</h3>
                    <p class="m-0"><strong>Total:</strong> £{{ order.order_total }}</p>
                    <p class="m-0"><strong>Delivery:</strong> £{{ order.delivery_cost }}</p>
                    <p class="m-0"><strong>Grand Total:</strong> £{{ order.grand_total }}</p>
                </div>
                <a class="white-btn px-3 py-1" href="{% url 'manage-site' %}">Back to Manage</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

manage_site/templates/manage_site/product-add.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'manage_site/css/manage-site.css' %}">
{% endblock %}

{% block content %}

<section class="admin-section">
    <div class="container">
        <div class="row">
            <div class="mx-auto col-12 col-md-6 admin-form rounded mt-3">
                <h2>Add Product</h2>
                <form class="productForm" method="POST">
                    {% csrf_token %}
                    {{ form.category | as_crispy_field }}
                    {{ form.name | as_crispy_field }}
                    {{ form.slug | as_crispy_field }}
                    {{ form.desc| as_crispy_field }}
                    <p class="mb-0">Sized Item:</p>
                    <div class="form-check form-switch" id="div_id_has_sizes">
                        <input class="form-check-input" name="has_sizes" type="checkbox" id="flexSwitchCheckDefault" checked="">
                    </div>
                    <div class="d-flex mt-2 justify-content-between">
                        {{ form.price | as_crispy_field }}
                        {{ form.sale_price | as_crispy_field }}
                    </div>
                    {{ form.image_url | as_crispy_field }}
                    <input class="shop-btn px-3 py-1 mb-3" type="submit" value="Add Product">
                </form>
            </div>
        </div>
    </div>

</section>

{% endblock %}

{% block postloadjs %}
<script src="{% static 'manage_site/js/product_form.js' %}"></script>
{% endblock %}

manage_site/templates/manage_site/product-delete.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'manage_site/css/manage-site.css' %}">
{% endblock %}

{% block content %}

<section class="admin-section">
    <div class="container">
        <div class="row text-center">
            <div class="p-3 bg-white mx-auto col-12 col-md-6 admin-form rounded">
                <h2>Delete Product</h2>
                <p>Are you sure you want to delete <strong>{{ object }}</strong>?</p>
                <div>
                    <img class="product-img" src="{{ object.image_url }}" alt="">
                    <p class="mt-2 fw-bold">ID: {{ object.id }}</p>
                    <p class="fw-bold">£{{ object.price }}</p>
                </div>
                
                <form method="post">{% csrf_token %}
                    {{ form }}
                    <a class="white-btn px-3 py-1" href="{% url 'manage-site' %}">Cancel</a>
                    <input class="shop-btn px-3 py-1" type="submit" value="Confirm">
                </form>
            </div>
        </div>
    </div>

</section>

{% endblock %}

manage_site/templates/manage_site/product-update.html
{% extends "base.html" %}
{% load static %}

{% load l10n %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'manage_site/css/manage-site.css' %}">
{% endblock %}

{% block content %}

<section class="admin-section">
    <div class="container">
        <div class="row">
            <div class="mx-auto col-12 col-md-6 admin-form rounded mt-3">
                <h2>Update Product</h2>
                <form class="productForm" method="POST">
                    {% csrf_token %}
                    {{ form.category | as_crispy_field }}
                    {{ form.name | as_crispy_field }}
                    {{ form.slug | as_crispy_field }}
                    {{ form.desc| as_crispy_field }}
                    <p class="mb-0">Sized Item:</p>
                    <div class="form-check form-switch" id="div_id_has_sizes">
                        <input class="form-check-input" name="has_sizes" type="checkbox" id="flexSwitchCheckDefault" checked="">
                    </div>
                    <div class="d-flex mt-2 justify-content-between">
                        {{ form.price | as_crispy_field }}
                        {{ form.sale_price | as_crispy_field }}
                    </div>
                    {{ form.image_url | as_crispy_field }}
                    <input class="shop-btn px-3 py-1 mb-3" type="submit" value="Update Product">
                </form>
            </div>
        </div>
    </div>

</section>

{% endblock %}

{% block postloadjs %}
<script src="{% static 'manage_site/js/product_form.js' %}"></script>
{% endblock %}

manage_site/templates/manage_site/profile-delete copy.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'manage_site/css/manage-site.css' %}">
{% endblock %}

{% block content %}

<section class="admin-section">
    <div class="container">
        <div class="row text-center">
            <div class="p-3 bg-white mx-auto col-12 col-md-6 admin-form rounded mt-3">
                <h2>Delete User Profile</h2>
                <p>Are you sure you want to delete User: <strong>{{ user }}</strong>?</p>
                <div>
                    <p class="mt-2 fw-bold">{{ user.first_name }} {{ user.last_name }}</p>
                    <p class="fw-bold">{{ user.email }}</p>
                </div>
                
                <form method="post">{% csrf_token %}
                    {{ form }}
                    <a class="white-btn px-3 py-1" href="{% url 'manage-site' %}">Cancel</a>
                    <input class="shop-btn px-3 py-1" type="submit" value="Confirm">
                </form>
            </div>
        </div>
    </div>

</section>

{% endblock %}
{% block postloadjs %}
{{ block.super }}
<script type="text/javascript">
</script>
{% endblock %}

manage_site/templates/manage_site/profile-delete.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'manage_site/css/manage-site.css' %}">
{% endblock %}

{% block content %}

<section class="admin-section">
    <div class="container">
        <div class="row text-center">
            <div class="p-3 bg-white mx-auto col-12 col-md-6 admin-form rounded mt-3">
                <h2>Delete User Profile</h2>
                <p>Are you sure you want to delete User: <strong>{{ user }}</strong>?</p>
                <div>
                    <p class="mt-2 fw-bold">{{ user.first_name }} {{ user.last_name }}</p>
                    <p class="fw-bold">{{ user.email }}</p>
                </div>
                
                <form method="post">{% csrf_token %}
                    {{ form }}
                    <a class="white-btn px-3 py-1" href="{% url 'manage-site' %}">Cancel</a>
                    <input class="shop-btn px-3 py-1" type="submit" value="Confirm">
                </form>
            </div>
        </div>
    </div>

</section>

{% endblock %}